version: '3.7'

x-airflow-common: &airflow-common
  image: apache/airflow:2.10.4-python3.10
  build:
    context: .
  env_file: .env
  volumes:
    - ./dags:/opt/airflow/dags
    - ./logs:/opt/airflow/logs
    - ./plugins:/opt/airflow/plugins
    - ./sql:/opt/airflow/sql
  user: "${AIRFLOW_UID:-50000}:0"

services:

  postgres:
    image: postgres:13
    container_name: airflow-postgres
    restart: always
    env_file: .env
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  airflow-init:
    <<: *airflow-common
    container_name: airflow-init
    entrypoint: /bin/bash
    command:
      - -c
      - |
        echo "🔧 Inicializando banco de dados do Airflow..."
        airflow db migrate
        airflow users create \
          --username admin \
          --password admin \
          --firstname Airflow \
          --lastname Admin \
          --role Admin \
          --email admin@example.com
        airflow connections create-default-connections
        echo "✅ Banco de dados pronto."

  webserver:
    <<: *airflow-common
    container_name: airflow-webserver
    command: webserver
    ports:
      - "8080:8080"
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    restart: always

  scheduler:
    <<: *airflow-common
    container_name: airflow-scheduler
    command: scheduler
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    restart: always

volumes:
  postgres-db-volume:
